### ISSUE TITLE
Fail gracefully when using less than PHP 5.4

### ISSUE THREAD

**Issue by fjarrett** [xwp/wp-dev-lib#101]
Users with PHP 5.3.29 or lower will receive a fatal error when attempting to generate markdown for `README.md` and may not know why:

```
PHP Fatal error: Using $this when not in object context in /wordpress-trunk/wp-content/plugins/my-plugin/dev-lib/class-wordpress-readme-parser.php on line 121
```

Either this should fail gracefully with an exception message, or compatibility with lower PHP versions should be considered.

**Comment by westonruter** [comment]
Good call. It needs to explicitly pass in the context to the closure, for instance:

```diff
+ $that = $this;
  
  // Parse sections
  $section_formatters = array(
- 	'Screenshots' => function ( $body ) {
+ 	'Screenshots' => function ( $body ) use ( $that ) {
```

And then use `$that` instead of `$this`. This is a limitation in PHP 5.3, but one which is all too familiar in JS land :smile:
