### ISSUE TITLE
Use SVG version of Travis-CI badge for high-resolution displays

### ISSUE THREAD

**Issue by fjarrett** [xwp/wp-dev-lib#109]
I think the Travis-CI badge generated in the README markdown should use the SVG version in order to better support high-resolution displays.

**COMPARISON**

<img width="100" alt="screen shot 2015-10-16 at 10 26 39 am" src="https://cloud.githubusercontent.com/assets/522158/10545851/696e49de-73f0-11e5-9eb9-c77663f3e1bc.png"> <img width="100" alt="screen shot 2015-10-16 at 10 26 29 am" src="https://cloud.githubusercontent.com/assets/522158/10545850/696c4210-73f0-11e5-891f-5df870d6f544.png">

**Comment by westonruter** [comment]
Thank you!
