### ISSUE TITLE
Broken Coveralls support?

### ISSUE THREAD

**Issue by ocean90** [xwp/wp-dev-lib#152]
In 13db3de669402566fdb9f10ef6b461d2dce6b23f support for Coveralls was added.

Today I tried to include the file in the repo for GlotPress via https://github.com/GlotPress/GlotPress-WP/commit/2b79c989d4d34b8a92e86b392f8418d995c98353 and https://github.com/GlotPress/GlotPress-WP/commit/a0045d0c27efd0e8a7d52c94fdfcfae2c77b6f36, but it seems like the config file is now longer valid, see https://travis-ci.org/GlotPress/GlotPress-WP/builds/115695816. 

I took a look at another repo and found https://github.com/xwp/wp-customize-posts/commit/a7fa4f5fe56a9dcad046be6681092bf88c9eecfd which doesn't include the line `src_dir: .`.
Should this be changed in the default .coveralls.yml file?

**Comment by westonruter** [comment]
Good question. I actually don't recall symlinking to the `.coveralls.yml` file but instead copying it along with the `.travis.yml`. But to be honest, I only have a limited familiarity with Coveralls. 

@valendesigns Should the `src_dir` be removed?
@ocean90 In the mean time, if you copy the file instead of symlink, does it then work?

**Comment by ocean90** [comment]
I haven't tested that, but it looks like the option got removed in 1.0.0, see https://github.com/satooshi/php-coveralls/blob/master/CHANGELOG.md#100.

**Comment by aristath** [comment]
I struggled getting coveralls to play nicely with my repos as well and in the end I just went for codecov instead. It's simpler and tbh it's also a lot better... You can even see the coverage on github directly :+1: https://github.com/codecov/browser-extension

**Comment by ocean90** [comment]
Well, coveralls [works](https://travis-ci.org/GlotPress/GlotPress-WP/jobs/115723609) without the `src_dir` value, but I agree that codecov looks much better.

Maybe provide a flag do decide which service should be used for coverage?

Example Project: https://codecov.io/github/WP-API/WP-API?branch=develop
Example Config: https://github.com/codecov/example-php/blob/master/.travis.yml
