### ISSUE TITLE
parse_ini_file() doesn't work with bash files

### ISSUE THREAD

**Issue by ocean90** [xwp/wp-dev-lib#160]
`generate-markdown-readme` loads `.dev-lib` via `parse_ini_file()` in https://github.com/xwp/wp-dev-lib/blob/fb7c84b7d76ea12eb8e8d03e77e756521c0e82b5/generate-markdown-readme#L65-L70.

This seems not work with the code from #157:

```
PHP Deprecated:  Comments starting with '#' are deprecated in /plugins/gp-translation-propagation/.dev-lib on line 1 in /plugins/gp-translation-propagation/dev-lib/generate-markdown-readme on line 70
PHP Warning:  syntax error, unexpected '{' in /plugins/gp-translation-propagation/.dev-lib on line 3
 in /plugins/gp-translation-propagation/dev-lib/generate-markdown-readme on line 70
Successfully converted WordPress README to Markdown
fatal: Pathspec '/plugins/gp-translation-propagation/dev-lib/generate-markdown-readme' is in submodule 'dev-lib'
```

**Comment by westonruter** [comment]
Humm, good to know. I see in the PHP.net info on `parse_ini_file()` that these are unsupported entirely in `7.0.0`:

> Hash marks (#) are no longer recognized as comments.

And alas, putting anything other than simple variable assignments will also fail (such as a Bash function) for parsing with `parse_ini_file()`. So the workaround to re-use `parse_ini_file()` as a workaround for parsing variables out of a Bash script is no longer going to work.

**Comment by westonruter** [comment]
@ocean90 how does #161 work for you?
