### ISSUE TITLE
Filter out .mailmap

### ISSUE THREAD

**Issue by chacha** [xwp/wp-dev-lib#180]
From [this issue](https://github.com/xwp/stream/issues/850) on Stream:

> Noticed the .mailmap file in the zip download from wordpress.org. Not sure what your process is for exporting to svn, but should probably get included in the exclusion list.

Might be worth adding the `.mailmap` file to the exclusion list as it is no longer as useful when you've stripped away the git commit log.

**Comment by jamesgol** [comment]
Didn't realize the wp-dev-lib library took care of this, so I added a PR for it.
