### ISSUE TITLE
Interactive installer

### ISSUE THREAD

**Issue by shadyvb** [xwp/wp-dev-lib#199]
It'd make the toolkit more accessible if we have an interactive installer that copies required files, installs the pre-commit plugin, and possibly install tools like PHPCS, WPCS, etc to the system as well.

**Comment by westonruter** [comment]
Great idea!

**Comment by kasparsd** [comment]
@shadyvb This is now possible with the npm support #207 added in #208. It will also automatically install the required libraries in the virtual machine and run the checks.
