### ISSUE TITLE
Format code for Github use

### ISSUE THREAD

**Issue by jonathanbardo** [xwp/wp-dev-lib#20]
It would be nice to have a way to format single quote code block from readme.txt into triple quote code block for Github use.

So :
`<?php echo 'hello'; ?>`

Would appear in readme.md :
```php
<?php echo 'hello'; ?>
```

**Comment by westonruter** [comment]
We finally got to this in #67, but I didn't see the note here about `~~~lang`. Is this still an advantage?

**Comment by westonruter** [comment]
Gonna close this. A PR can be opened with the change for `~~~` if it is desired.
