### ISSUE TITLE
DEV_LIB_PATH is ignored when running in Vagrant

### ISSUE THREAD

**Issue by kasparsd** [xwp/wp-dev-lib#210]
[Here we assume](https://github.com/xwp/wp-dev-lib/blob/f4604c83cb273353966ac324ee4b541546783cbf/check-diff.sh#L599) that `pre-commit` is in `dev-lib` instead of relying on the `$DEV_LIB_PATH`.

Suggested fix #209.

**Comment by westonruter** [comment]
Merged #209. Thanks!
