### ISSUE TITLE
Support PHPUnit when it's a Composer dependency

### ISSUE THREAD

**Issue by johnbillion** [xwp/wp-dev-lib#236]
I have a project where PHPUnit is a Composer dependency because we need to control the version of PHPUnit that's used.

It looks like dev-lib checks for the phpunit binary before manually downloading and installing it if necessary. It would be great if dev-lib could also check for `vendor/bin/phpunit` too, and use it if it's present.

**Comment by westonruter** [comment]
Yes, good call. Similar to what has been done with using binaries installed locally via NPM, e.g. #215.

**Comment by kasparsd** [comment]
Fixed in #254.
