### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jhabdas** [xwp/wp-dev-lib#237]
As it stands this repo is without license. Please add a license.

**Comment by jhabdas** [comment]
https://blog.codinghorror.com/pick-a-license-any-license/

**Comment by valendesigns** [comment]
We can definitely add a GLP license. Thanks for the request.

**Comment by jhabdas** [comment]
Thanks. Whether you choose to copyleft or right will allow me to use this software legally, and I would appreciate using some of this software. Cheers.

**Comment by jhabdas** [comment]
Thanks for the quick turnaround @westonruter

**Comment by jhabdas** [comment]
FYI - https://hackernoon.com/introducing-the-btc-license-28650887eb11
