### ISSUE TITLE
Apply licensing to source code

### ISSUE THREAD

**Issue by jhabdas** [xwp/wp-dev-lib#240]
#237 took the licensing part way there, but missed a couple of important points on making this code usable to the public.

To understand how to _apply_ the GPL to your source code please see the following:
https://choosealicense.com/licenses/gpl-2.0/

Also, it may be wise to consider one of [the other licenses](https://choosealicense.com/licenses/), such as GPL-3.0, LGPL or AGPL as GPL-2, unless applied using `+`, has some holes in it.

**Comment by jhabdas** [comment]
For the sake of clarity:

> **Note:** The Free Software Foundation recommends taking the additional step of adding a boilerplate notice to the top of each file. The boilerplate can be found at the end of the license.

**Comment by westonruter** [comment]
I added the license via the facility that GitHub provides for adding a license to a project. I chose GPLv2 because it is the license used in WordPress.

**Comment by jhabdas** [comment]
Weston. Sorry I should have been less wordy, hence the follow-up comment regarding applying the license. When I originally requested its addition I was hoping to leverage `wp-tools` but got blocked due to some files used in their repo without the GPL headers applied.

Here's the related issue adding the headers will allow them to resolve: https://github.com/gedex/wp-tools/issues/35

**Comment by jhabdas** [comment]
> I added the license via the facility that GitHub provides for adding a license to a project. I chose GPLv2 because it is the license used in WordPress.

Given most of these tools will be used in applications _outside_ of WordPress, but to _create_ things for WordPress, it may be preferable to change to an MIT or ISC license type, example:

https://github.com/antecedent/patchwork/blob/master/Patchwork.php#L3-L7

**Comment by jhabdas** [comment]
Update. GNU AGPL licenses, a stronger copyleft license than the GPLv3, should be fine for use in WordPress themes and plugins. If the foundation tries and block them please direct attention here:
https://github.com/comfusion/hyperdrive/issues/41#issuecomment-304381094

I have lines out to both the Free Software Foundation and Software Freedom Law Center whom I will use to validate my finding for the benefit of openness and progressive nature of all source plugins and themes created for and used in WordPress.

/cc @ntwb

**Comment by ntwb** [comment]
As I stated in the issue in your repo @jhabdas I wrote that it was incredibly impolite to ping people in your issues who have nothing to do with your project, you took it upon yourself to delete that comment and email me the following reason:

> _"I removed your comment in my repo because it was not conducive to discussion."_

I'm writing this here because you cannot delete this comment.

Please do not ping me again in any of your issues, this goes for pinging any other WordPress contributor who is not involved in your project directly.

As to the specifics of the issue here for the `wp-dev-lib` repo, a license has been added and the issue is closed, now leave it alone.
