### ISSUE TITLE
Update `.editorconfig` and `*.json` files to use tabs for indentation

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-dev-lib#244]
See https://core.trac.wordpress.org/ticket/40946

**Comment by mehigh** [comment]
I'll test this along the work in https://github.com/xwp/wp-dev-lib/pull/245 and if it all works OK, I'll get it merged in.

**Comment by ntwb** [comment]
@westonruter  @mehigh This issue can be closed, the change was merged in https://github.com/xwp/wp-dev-lib/commit/49484a476f01228fdefa00f3b9c18a277f6a2061
