### ISSUE TITLE
Allow adding PHPCS installed_paths config

### ISSUE THREAD

**Issue by igmoweb** [xwp/wp-dev-lib#260]
Sometimes you could need to add different sets of rules than the common ones for PHPCS. I'd like to ask for a variable in .dev-lib that would allow defining routes for PHPCS configuration.

Right now, the only way to hack those paths is to change the `$WPCS_DIR` variable. `check-diff.sh` contains the following line:

`phpcs --config-set installed_paths $WPCS_DIR`

It would be nice if we had a similar line at the end of `install_tools` function, something like this (if $PHPCS_PATHS is not empty):

`phpcs --config-set installed_paths $WPCS_DIR,$PHPCS_PATHS`

Thanks

**Comment by westonruter** [comment]
Hi. Would not what is added in #254 solve your problem?

Your exact problem was discussed there: https://github.com/xwp/wp-dev-lib/pull/254#discussion_r132579926

**Comment by igmoweb** [comment]
Thanks @westonruter 

Yes, it's more or less the same problem. In our case, we were trying to add `fig-r/psr2r-sniffer` sniffs but it seems that `phpcodesniffer-composer-installer` isn't loading them automatically. We just needed one rule so I ended up using the following rule in our `phpcs.ruleset.xml`. Here's the example:

```<rule ref="./vendor/fig-r/psr2r-sniffer/PSR2R/Sniffs/ControlStructures/NoInlineAssignmentSniff.php"/>```

Eventually, the rule must be loaded via php path. I haven't been able to load it by using another method.

I hope it helps to someone else.

**Comment by igmoweb** [comment]
I forgot to add `composer.json` requires:

```"require-dev": {
        "wp-coding-standards/wpcs": "*",
        "wimg/php-compatibility": "*",
        "squizlabs/php_codesniffer": "2.9.0",
        "fig-r/psr2r-sniffer": "^0.4.1",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.4.2"
    }```

We had to use `squizlabs/php_codesniffer` 2.9.0 because of an incompatibility with `wp-coding-standards/wpcs`.

We're loading `wp-dev-lib` as a submodule.

Thanks!

**Comment by westonruter** [comment]
>  it seems that phpcodesniffer-composer-installer isn't loading them automatically

Yes, that's right. It's not added automatically.

> Eventually, the rule must be loaded via php path. I haven't been able to load it by using another method.

Humm. This is what `phpcodesniffer-composer-installer` is supposed to eliminate the need for.

> We just needed one rule so I ended up using the following rule in our phpcs.ruleset.xml

BTW, I recommend renaming this file to `phpcs.xml`. When you do this, then you can call `phpcs` on the command line without any args and it will automatically use it as the ruleset to check against. See #243.

**Comment by igmoweb** [comment]
Thanks for your help @westonruter It's rare that `phpcodesniffer-composer-installer` is not loading those rules but I need to investigate further about that.

I'm going to close here and opening another one if I see anything else.

Thanks again.
