### ISSUE TITLE
Downloading PHPUnit twice ?

### ISSUE THREAD

**Issue by jrfnl** [xwp/wp-dev-lib#267]
Just wondering - I might well be reading the code incorrectly -, but by the looks of it, PHPUnit is potentially downloaded & installed twice ?

There may be an efficiency fix which can be made here or else a de-duplication.

https://github.com/xwp/wp-dev-lib/blob/61a4add397effac047f2ffe015d600ebd2db0ffe/travis.install.sh#L14-L19

https://github.com/xwp/wp-dev-lib/blob/61a4add397effac047f2ffe015d600ebd2db0ffe/check-diff.sh#L444-L447

**Comment by kasparsd** [comment]
Fixed in #301.

**Comment by jrfnl** [comment]
:tada:
