### ISSUE TITLE
Start versioning wp-dev-lib

### ISSUE THREAD

**Issue by kasparsd** [xwp/wp-dev-lib#277]
With the added support for Composer in #273 we can start tagging releases according to [SemVer](https://semver.org/). This should also help us with introducing breaking changes to the project, if necessary.

**Comment by westonruter** [comment]
And we can start using a `develop` branch as well.

**Comment by kasparsd** [comment]
@westonruter What's the thinking behind a `develop` branch? Could we keep `master` as the development branch and tag the releases whenever they're ready?

**Comment by westonruter** [comment]
The idea being that there could be a stable branch, `master`, and a bleeding edge branch, `develop`.

**Comment by kasparsd** [comment]
Sounds good @westonruter! Would we then open pull requests against `master` or `develop`?

**Comment by westonruter** [comment]
We'd probably change the default branch to `develop` and open pull requests against it. Then when doing a new version bump we could merge `develop` into `master`.

**Comment by kasparsd** [comment]
Fixed with #278.
