### ISSUE TITLE
Check text-domain compliance

### ISSUE THREAD

**Issue by shadyvb** [xwp/wp-dev-lib#32]
- [ ] Check if a text-domain header exists ( if is a plugin / theme )
- [ ] Check all instances of translation functions to confirm the text domain is typed correctly

**Comment by westonruter** [comment]
This is now part of PHPCS.

**Comment by shadyvb** [comment]
@westonruter Is this documented somewhere ?

I'm assuming we can use [PHPCS syntax](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml) to pass the text domain as a property to the sniff ? ie: 
```
<rule ref="WordPress.Sniffs.WP.I18n">
  <properties>
   <property name="text_domain" value="my_slug"/>
  </properties>
</rule>
```

Would be a great addition to the interactive installer in #199 , and a hint in the bundled ruleset would be awesome as well ( can PR that if you confirm this is the right way to do it ).

**Comment by westonruter** [comment]
Yeah, you can see an example here: https://github.com/xwp/wp-customize-posts/blob/f2a9eb47ff45d6f00d86d62890b06dbdbee89d49/phpcs.ruleset.xml#L5-L10

And yes, this would be a good thing to add to an interactive installer. The installer could ask if it's a VIP project, and if so, use `WordPress-VIP` standard in the ruleset, or else use `WordPress-Extra` (or `WordPress-Core`). And then it could confirm the text domain for whether it's a theme or plugin.
