### ISSUE TITLE
exclude assets folder

### ISSUE THREAD

**Issue by desaiuditd** [xwp/wp-dev-lib#60]
Not sure whether this is an issue or not. But I was facing it and I had to fix it with patch-work.

There's an exclude flag in rsync to fetch repo files from git into svn. [Ref](https://github.com/xwp/wp-dev-lib/blob/master/svn-push#L109).

So what is this doing is; excluding all the `assets` folder from the repository; and not just the one which is required for banners & screenshots. For example, in my plugin; I'm putting my JS, CSS etc. into `app/assets/` folder. Also I've used a few vendor libraries in which assets folder is used. So `svn-push` script ignores all these folders along with the one with banners; resulting in partial file uploads in WordPress.org SVN repo. And this eventually breaks the plugin functionality.

So what I did to prevent this is; removed the exclude flag for assets from rsync and after that I removed assets folder from svn trunk using `rm`.

Though this worked for me, I had a hunch that either I'm doing something wrong or missing something in order to use this script.

Suggestions ?

**Comment by desaiuditd** [comment]
Hi @westonruter ,

Yup. That worked for me. Thanks. :smile:

**Comment by desaiuditd** [comment]
Do you think this should go in script ?

**Comment by westonruter** [comment]
@desaiuditd yes, would you mind opening a PR to make that change? I'm heading to bed :smile:

**Comment by westonruter** [comment]
Nevermind, hah. Let me throw it up...

**Comment by desaiuditd** [comment]
Yeah. I'll do it. :+1:

**Comment by desaiuditd** [comment]
Oh. Thanks :)
