### ISSUE TITLE
svn-push script error after readme parse

### ISSUE THREAD

**Issue by desaiuditd** [xwp/wp-dev-lib#61]
I already have setup pre-commit hook where readme.txt is getting parsed on each commit. Of course if there are any changes.

So when i release my plugin on WordPress.org using `svn-push` script, it has nothing new to parse in readme.txt and readme.md stays intact as it is.

And then `svn-script` throws this error and exits.

```
Please commit (--amend?) the updated readme.md
```

When I try `git status` it gives me `readne.md` in unstaged section. Like below:

![screenshot from 2015-01-02 13 16 16](https://cloud.githubusercontent.com/assets/2236554/5594931/3a57cd2a-928a-11e4-87b6-cbe7c8eba4a7.png)
 
I see an if condition [here](https://github.com/xwp/wp-dev-lib/blob/master/svn-push#L44). What could be the significance of it ? Am I missing something here ?

**Comment by westonruter** [comment]
Actually, it shows that the changes to `readme.md` *have* been staged. What does `git diff --staged` show?

**Comment by desaiuditd** [comment]
Ah ! Got the issue. I had used HTTP clone url. So it was updating the travis badge url & then not commiting it.

Can we support HTTP clone url as well along with SSH clone url ?

**Comment by desaiuditd** [comment]
Usually, I release the plugin from a cloud server where there are less chances of loosing the network connectivity. So that release doesn't get stuck in between. And server does not have its ssh key added in the repository.

So do you suggest any workaround there ?

**Comment by westonruter** [comment]
@desaiuditd are you using the version of `svn-push` as of 26 days ago? You can see in the RegEx for the GitHub URL that it should be supporting HTTP and HTTPS, in addition to SSH: https://github.com/xwp/wp-dev-lib/blob/d328d444440cd3905d043c4407c12babc09dcecb/generate-markdown-readme#L43

**Comment by desaiuditd** [comment]
Oh ! Looks like I'm using an older version. I'll give it a try for latest version. You ma close this one. If I'm still stuck I'll re-open this.

**Comment by westonruter** [comment]
Cheers!
