### ISSUE TITLE
Support syntax highlighting in code blocks

### ISSUE THREAD

**Issue by fjarrett** [xwp/wp-dev-lib#67]
AFAIK the only way to achieve a code block in `readme.txt` is to use the `<pre>` tag.

It would be nice to add support for a `lang` attribute so that syntax highlighting can be added when converting to markdown.

**TXT**
```
<pre lang="php">
function foo() {
	$bar = 'baz';
}
</pre>
```

**Markdown**
```php
function foo() {
	$bar = 'baz';
}
```

**Comment by kucrut** [comment]
Hmm, you can already use backticks:

```
`
code...
`
```

**Comment by fjarrett** [comment]
Oh wow. To my surprise this already works! :smile: 

![screen shot 2015-01-03 at 11 39 18 am](https://cloud.githubusercontent.com/assets/522158/5603197/4a8728cc-933d-11e4-889f-40d06d156214.png)

![screen shot 2015-01-03 at 11 39 38 am](https://cloud.githubusercontent.com/assets/522158/5603198/4f15d4b0-933d-11e4-9abd-4b8009cdc5d2.png)

**Comment by fjarrett** [comment]
@kucrut That's what I thought too, but single backticks were breaking the page when used in the FAQ tab on my WordPress.org plugin.

**Comment by fjarrett** [comment]
I'm going to reopen this because I do think there is some slight room for improvement.

It would be cleaner if `<pre lang="php">` converted to ```php in markdown.

**Comment by westonruter** [comment]
So `<pre lang="php">` is part of the WP `readme.txt` “standard”? I don't see it mentioned on https://wordpress.org/plugins/about/readme.txt

Is it a hidden feature?

**Comment by fjarrett** [comment]
@westonruter Not sure if it's part of the "standard", but it does seem to work.

**Comment by westonruter** [comment]
That's great. I was wondering how we could implement that.

**Comment by westonruter** [comment]
@fjarrett let me know how #68 works for you.
