### ISSUE TITLE
Set the correct MIME type for assets on SVN commit

### ISSUE THREAD

**Issue by fjarrett** [xwp/wp-dev-lib#70]
As explained in [this article](http://wptavern.com/plugin-authors-how-to-avoid-download-prompts-associated-with-screenshots-on-the-wordpress-plugin-directory) on WP Tavern:

> If you’ve ever clicked on a screenshot in the WordPress plugin directory and received a download prompt, you’re not the only one. In fact, it’s a widespread issue that affects a number of plugins. The prompt appears for images that use the incorrect MIME Type.

**Comment by westonruter** [comment]
@fjarrett try out #71.
