### ISSUE TITLE
Prefer secure URIs when generating README

### ISSUE THREAD

**Issue by fjarrett** [xwp/wp-dev-lib#72]
I think we should use secure URIs whenever possible.

Ex: https://wordpress.org, https://www.youtube.com, https://profiles.wordpress.org

**Comment by fjarrett** [comment]
@westonruter Issue stealer... :smile:

**Comment by westonruter** [comment]
Sorry. You didn't self assign it :smile:

**Comment by fjarrett** [comment]
@westonruter Actually, I did :smile: 

![screen_shot_2015-01-10_at_3_07_08_pm](https://cloud.githubusercontent.com/assets/522158/5693250/6f23415a-98da-11e4-888c-915c8d2faadd.png)

**Comment by westonruter** [comment]
BLAST. Sorry. I didn't even look. Shame on me. :frowning:

**Comment by fjarrett** [comment]
I forgive you. :smile_cat:
