### ISSUE TITLE
GitHub release tag not created after SVN push

### ISSUE THREAD

**Issue by fjarrett** [xwp/wp-dev-lib#78]
I've noticed that after running `svn-push` an SVN tag is created properly but a GitHub release tag is not.

I believe in the past a GitHub tag was being created.

Am I doing something incorrect or is this a bug?

**Comment by westonruter** [comment]
@fjarrett it should be creating the release tag just fine: https://github.com/xwp/wp-dev-lib/blob/88d464667aa4859e285f62010f7a7b75e96f3385/svn-push#L169-L177

**Comment by fjarrett** [comment]
@westonruter OK thanks for confirming that it should be.

I had to create a tag manually for Stream because I noticed it wasn't there.

I've checked all my recent plugin projects and none of them have GitHub tags. Not sure what I am doing wrong, but I must be doing it wrong everywhere. #ibreakthings :smile_cat: 

https://github.com/fjarrett/archived-post-status/releases
https://github.com/fjarrett/user-session-control/releases
https://github.com/fjarrett/prevent-concurrent-logins/releases
https://github.com/fjarrett/json-rest-api-force-ssl/releases
https://github.com/fjarrett/compact-view-mode

**Comment by westonruter** [comment]
Next time you do a release, can you include the script output? 

Are the tags getting created locally, but just not pushed to GitHub?

**Comment by westonruter** [comment]
If the tags were created locally, then you could push then *en mass* via `git push --tags`

**Comment by fjarrett** [comment]
@westonruter That did the trick: https://github.com/fjarrett/archived-post-status/releases

**Comment by westonruter** [comment]
But it looks like maybe the `svn-push` script should make this change:

```diff
- git push origin "$plugin_version"
+ git push origin tag "$plugin_version"
```

**Comment by fjarrett** [comment]
:+1:

**Comment by westonruter** [comment]
If that fixes the problem, then please open a PR with that change.

**Comment by westonruter** [comment]
I don't see my above syntax from http://stackoverflow.com/a/2988182/93579

Mentioned on http://git-scm.com/book/en/v2/Git-Basics-Tagging#Sharing-Tags

So I'm confused.

**Comment by fjarrett** [comment]
Maybe the method used in the docs requires Git 2.0? I am using 1.9.3.

**Comment by westonruter** [comment]
Oh, I see it mentioned in the `--help` for `git push`:

> tag <tag> means the same as refs/tags/<tag>:refs/tags/<tag>.

So go ahead and try adding the above change with your next push, and see what happens!

**Comment by fjarrett** [comment]
I just pushed a new release on a plugin and that line change didn't work. The tag was not pushed to GitHub.

**Comment by fjarrett** [comment]
Console output:

```
$ dev-lib/svn-push -f
Successfully converted WordPress README to Markdown
/Users/frankie/Dropbox/Sites/vvv/www/wordpress-trunk/wp-content/plugins/archived-post-status/readme.md
From github.com:fjarrett/archived-post-status
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Everything up-to-date
dev-lib/svn-push: line 52: md5sum: command not found
dev-lib/svn-push: line 53: md5sum: command not found
Temp SVN dir: /tmp/svn-archived-post-status-
Temp Git dir: /tmp/git-archived-post-status-
Updating '.':
At revision 1072910.
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 22 (delta 15), reused 0 (delta 0)
Unpacking objects: 100% (22/22), done.
From /Users/frankie/Dropbox/Sites/vvv/www/wordpress-trunk/wp-content/plugins/archived-post-status
   8a4b950..52cecaf  master     -> origin/master
 * [new branch]      feature/readonly-mode -> origin/feature/readonly-mode
Updating 8a4b950..52cecaf
Fast-forward
 archived-post-status.php |  98 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------
 assets/screenshot-1.png  | Bin 23293 -> 23183 bytes
 assets/screenshot-3.png  | Bin 12447 -> 14142 bytes
 readme.md                |  25 ++++++++++++++++++++++++-
 readme.txt               |  28 +++++++++++++++++++++++++++-
 5 files changed, 124 insertions(+), 27 deletions(-)
building file list ... done
./
archived-post-status.php
readme.md
readme.txt

sent 5001 bytes  received 92 bytes  10186.00 bytes/sec
total size is 30344  speedup is 5.96
building file list ... done
./
screenshot-1.png
screenshot-3.png

sent 36565 bytes  received 70 bytes  73270.00 bytes/sec
total size is 58105  speedup is 1.59
Set mime-type image/png on all png files...
property 'svn:mime-type' set on 'assets/banner-1544x500.png'
property 'svn:mime-type' set on 'assets/banner-772x250.png'
property 'svn:mime-type' set on 'assets/icon-128x128.png'
property 'svn:mime-type' set on 'assets/icon-256x256.png'
property 'svn:mime-type' set on 'assets/screenshot-1.png'
property 'svn:mime-type' set on 'assets/screenshot-2.png'
property 'svn:mime-type' set on 'assets/screenshot-3.png'
Set mime-type image/jpeg on all jpg files...
Set mime-type image/jpeg on all jpeg files...
Set mime-type image/gif on all gif files...
M       assets/screenshot-1.png
M       assets/screenshot-3.png
A       tags/0.2.0
A       tags/0.2.0/LICENSE
A       tags/0.2.0/archived-post-status.php
A       tags/0.2.0/readme.md
A       tags/0.2.0/readme.txt
M       trunk/archived-post-status.php
M       trunk/readme.md
M       trunk/readme.txt

SVN Commit message:
Update to commit 52cecaf from git@github.com:fjarrett/archived-post-status.git

Hit enter to proceed with SVN commit and Git tag

Tagging plugin version 0.2.0
Total 0 (delta 0), reused 0 (delta 0)
To /Users/frankie/Dropbox/Sites/vvv/www/wordpress-trunk/wp-content/plugins/archived-post-status
 * [new tag]         0.2.0 -> 0.2.0
Sending        assets/screenshot-1.png
Sending        assets/screenshot-3.png
Adding         tags/0.2.0
Adding         tags/0.2.0/LICENSE
Adding         tags/0.2.0/archived-post-status.php
Adding         tags/0.2.0/readme.md
Adding         tags/0.2.0/readme.txt
Sending        trunk/archived-post-status.php
Sending        trunk/readme.md
Sending        trunk/readme.txt
Transmitting file data .........
Committed revision 1072911.
```

**Comment by westonruter** [comment]
Humm. This part:

```
Tagging plugin version 0.2.0
Total 0 (delta 0), reused 0 (delta 0)
To /Users/frankie/Dropbox/Sites/vvv/www/wordpress-trunk/wp-content/plugins/archived-post-status
 * [new tag]         0.2.0 -> 0.2.0
```

Makes it look like it is pushing the tag to a clone on your own system? Like `origin` is not a remote pointing to GitHub?

**Comment by fjarrett** [comment]
Here is my config:

![screen shot 2015-01-21 at 4 33 18 pm](https://cloud.githubusercontent.com/assets/522158/5846694/47d21d74-a18b-11e4-8d17-647d02f1b272.png)

**Comment by fjarrett** [comment]
You know what, I had the wrong branch checked out on `dev-lib` before I changed that line. I will try again on another plugin later.

**Comment by westonruter** [comment]
Actually, I'm getting the same issue. No releases: https://github.com/xwp/wp-widget-favorites/tags

So it's happening on my machine too. I'll try to debug on next release for Widget Favorites.

**Comment by fjarrett** [comment]
OK :smile:
