### ISSUE TITLE
Omit including Tags metadata in readme.md if no Tags supplied in readme.txt

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-dev-lib#81]
https://github.com/xwp/wp-dev-lib/blob/71c8a0f287126f8335aa3b4d7db945f5ab0df48f/class-wordpress-readme-parser.php#L153-L161

**Comment by Ritesh-patel** [comment]
@westonruter this has been fixed in 44ae78ed8b3b74d0e6350c8882c788f7cb8e460c and can be closed.

**Comment by westonruter** [comment]
Thanks!
