### ISSUE TITLE
Recent changes to install-wp-tests.sh in WP-CLI causing Travis builds to fail

### ISSUE THREAD

**Issue by fjarrett** [xwp/wp-dev-lib#91]
We are [referencing `install-wp-tests.sh` directly](https://github.com/xwp/wp-dev-lib/blob/master/travis.before_script.sh#L34) from the WP-CLI project in `travis.before_script.sh`.

And ever since [these changes](https://github.com/wp-cli/wp-cli/commit/55a7fe2172cca0094658851f444aff3387b9b909#diff-85) were merged into the WP-CLI master branch yesterday, I have been experiencing [build failures](https://travis-ci.org/wp-stream/stream/jobs/59789750#L909) related to the `/tmp/wordpress-tests/` dir.

```
PHP Warning:  require_once(/tmp/wordpress-tests/includes/functions.php): failed to open stream: No such file or directory in /tmp/wordpress/wp-content/plugins/stream/tests/bootstrap.php on line 17
```

**Comment by westonruter** [comment]
We're now including our own version of `install-wp-tests.sh`
